In [1]:
%matplotlib inline

from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import numpy as np
import matplotlib.pyplot as plt
import inspect
from sklearn.preprocessing import normalize

In [2]:
def g(category_one, category_two, category_three):
    frame = inspect.currentframe()
    args, _, _, values = inspect.getargvalues(frame)
    vals = [values[i] for i in args]
    total = sum(vals)
    pond = np.divide(vals, [total] * len(vals))
    return(pond)

interact(g,
    category_one   = widgets.IntSlider(min=0,max=10,step=1,value=5, continuous_update = False),
    category_two   = widgets.IntSlider(min=0,max=10,step=1,value=5, continuous_update = False),
    category_three = widgets.IntSlider(min=0,max=10,step=1,value=5, continuous_update = False)
)

array([ 0.41176471,  0.17647059,  0.41176471])

In [3]:
@interact(
    category_one   = widgets.IntSlider(min=-2,max=2,step=1,value=0, continuous_update = False),
    category_two   = widgets.IntSlider(min=-2,max=2,step=1,value=0, continuous_update = False),
    category_three = widgets.IntSlider(min=-2,max=2,step=1,value=0, continuous_update = False)
)

def g(category_one, category_two, category_three):
    frame = inspect.currentframe()
    args, _, _, values = inspect.getargvalues(frame)
    vals = [values[i] for i in args]
    exponents = []
    for val in vals:
        exponents.append(2**val)
    total = sum(exponents)
    results = np.divide(exponents, [total] * len(exponents))
    return(results)

array([ 0.44444444,  0.11111111,  0.44444444])

In [4]:
def g(one_vs_two, one_vs_three, two_vs_three):
    frame = inspect.currentframe()
    args, _, _, values = inspect.getargvalues(frame)
    vals = [values[i] for i in args]
    vals = np.divide(vals, 10)
    mat = np.empty([len(vals), len(vals)], dtype=float)
    cont = 0
    for i in range(0, len(vals)):
        for j in range(0, len(vals)):
            if(i == j):
                mat[i, j] = 1.0
            elif (i < j):
                mat[i, j] = vals[cont] / (1 - vals[cont])
                mat[j, i] = (1 - vals[cont]) / vals[cont]
                cont += 1
    print("Pairwise comparison matrix:")
    print(mat)
    print("\n")
    column_totals = np.apply_along_axis(sum, 0, mat)
    print("Column totals:")
    print(column_totals)
    print("\n")
    normalized_mat = normalize(mat, norm='l1', axis=0)
    print("Normalized matrix:")
    print(normalized_mat)
    print("\n")
    row_totals = np.apply_along_axis(sum, 1, normalized_mat)
    print("Absolute weights (row totals, 1st norm ev):")
    print(row_totals)
    print("\n")
    relative_weights = normalize(row_totals.reshape(1, -1), norm='l1')
    print("Absolute weights:")
    print(relative_weights)
    print("\n")
    return(None)
         
interact(g, 
    one_vs_two   = widgets.IntSlider(min=0.0,max=10.0,step=0.01,value=5, continuous_update = False),
    one_vs_three = widgets.IntSlider(min=0.0,max=10.0,step=0.01,value=5, continuous_update = False),
    two_vs_three = widgets.IntSlider(min=0.0,max=10.0,step=0.01,value=5, continuous_update = False)
)



Pairwise comparison matrix:
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


Column totals:
[ 3.  3.  3.]


Normalized matrix:
[[ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]


Absolute weights (row totals, 1st norm ev):
[ 1.  1.  1.]


Absolute weights:
[[ 0.33333333  0.33333333  0.33333333]]




<function __main__.g>